### ISSUE TITLE
Create a page to inform users about the app not having location permission.

### ISSUE THREAD

**Issue by Prince2347X** [Prince2347X/hope#14]
Here's what it should look like 
![IMG_20230720_161952](https://github.com/Prince2347X/hope/assets/68418241/49119f42-e8b4-48d0-9799-e7414f4371f9)

The 'Enter Location Manually' button is not required.
The color of the buttons and the image should follow out app theme.
(For image you can refer websites like undraw.co or use the following image: 
![undraw_My_location_re_r52x](https://github.com/Prince2347X/hope/assets/68418241/e33a0149-deba-4a3b-9679-d65976c1f8a5)

**Comment by Parthh08** [comment]
Done with #16
