### ISSUE TITLE
Design "Others" page

### ISSUE THREAD

**Issue by Prince2347X** [Prince2347X/hope#3]
## Design the "Others" page of the user side containing:

-----

User Section
- [ ] User profile information (editable)
- [ ] Edit profile
- [ ] Dark mode
- [ ] Language
- [ ] Become a Volunteer

------
App section

- [ ] Report bug/Feedback
- [ ] Rate us
- [ ] Share this app
- [ ] Privacy Policy
- [ ] Terms of Use
- [ ] Credits

**Comment by SujalSingh1704** [comment]
Planned for future
